-- local TweenService = game:GetService("TweenService")

-- local TimeToMove = script.Parent:GetAttribute("TimeToMove")
-- local EndPoint = script.Parent.Parent:FindFirstChild("EndPoint")

-- local instance = script.Parent
-- local tweenInfo = TweenInfo.new(TimeToMove, Enum.EasingStyle.Linear, Enum.EasingDirection.InOut, -1, true)
-- local goal = {}
-- goal.Position = Vector3.new(50, 10, 0)

-- local tween = TweenService:Create(instance, tweenInfo, goal)
-- tween:Play()
